### ISSUE TITLE
List is not updated on Edit

### ISSUE THREAD

**Issue by SarjitDelivala** [cs2103jan2015-f13-1j/main#23]
If a task is edited it is not updated in the list.

**Comment by SarjitDelivala** [comment]
![error](https://cloud.githubusercontent.com/assets/10009648/6638242/f64afc36-c9a9-11e4-80da-bbf31e1f6b05.png)
If a task is updated/edited after any exception is generated then it does not reflect in the list.

**Comment by darentzl** [comment]
This problem has been fixed. Please test it appropriately and re-open if there are any issues
